// Typed access to the sprite sheet generated by scripts/generate-sprites.mjs.
// Regenerate the sheet+atlas with `node scripts/generate-sprites.mjs`; this
// module just gives callers typed frame lookups instead of raw JSON access.

import atlasData from '../../public/sprites/atlas.json'

export type FrameName = keyof typeof atlasData.frames

export interface SpriteFrame {
  x: number
  y: number
  w: number
  h: number
}

// atlas.json stores a root-absolute path; Vite only rewrites asset URLs it
// can see at build time (import statements, CSS, index.html), not strings
// loaded from JSON, so this has to be joined with BASE_URL by hand to work
// under GitHub Pages' /space-weather-pixel/ subpath instead of just "/".
export const SPRITE_SHEET_URL =
  import.meta.env.BASE_URL.replace(/\/$/, '') + atlasData.sheet
export const SPRITE_CELL_SIZE = atlasData.cellSize

const frames = atlasData.frames as Record<FrameName, SpriteFrame>

export function getFrame(name: FrameName): SpriteFrame {
  return frames[name]
}

export const FRAME_NAMES = Object.keys(frames) as FrameName[]
